### ISSUE TITLE
Python error:  OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by Bzzzzz** [Oslandia/qgis-wasp#2]
Hi Vincent,

Thanks a lot for your feedback.
I follow your tips and get the result as below:

Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 80, in qgis_excepthook
    showException(type, value, tb, None)
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 77, in showException
    msg.showMessage()
KeyboardInterrupt

Looking forward your feedback!

(PS:
 Original exception was:

Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 80, in qgis_excepthook
    showException(type, value, tb, None)
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 77, in showException
    msg.showMessage()
KeyboardInterrupt
)

Pengyu

**Comment by vmora** [comment]
This look very strange to me, you should see in the terminal you are running qgis from, or in the python console, the command line that is sent to the system to run ogr2ogr.

**Comment by Bzzzzz** [comment]
The output of print cmd is:
[u'/home/pengyu', '-skipfailures', '-overwrite', '-f', 'ESRI Shapefile', u'/tmp/creyap_rou.shp', u'/home/pengyu/Documents/ZT0.8/creyap_input_files/creyap_rou.map']

Yes, I do it in the terminal running qgis, but it does work. Is it possible caused by the wrong command? I am sorry but I am freshman for this.

**Comment by Bzzzzz** [comment]
The output of print cmd is:
[u'/home/pengyu', '-skipfailures', '-overwrite', '-f', 'ESRI Shapefile', u'/tmp/creyap_rou.shp', u'/home/pengyu/Documents/ZT0.8/creyap_input_files/creyap_rou.map']

Yes, I do it in the terminal running qgis, but it does work. Is it possible caused by the wrong command? I am sorry but I am freshman for this.

**Comment by Bzzzzz** [comment]
If I configure the org2org path, the cmd will be:
[u'/usr/bin/ogr2ogr', '-skipfailures', '-overwrite', '-f', 'ESRI Shapefile', u'/tmp/creyap_rou.shp', u'/home/pengyu/Documents/ZT0.8/creyap_input_files/creyap_rou.map']

With the error in wasp.err like this: 
/usr/bin/ogr2ogr: /usr/local/lib/libgdal.so.1: no version information available (required by /usr/bin/ogr2ogr)

**Comment by Bzzzzz** [comment]
Good news. I changed the line:
 cmd = [self.ogr2ogr,'-skipfailures','-overwrite','-f',"ESRI Shapefile",shpDir,mapFile]
by
cmd = ['ogr2ogr','-skipfailures','-overwrite','-f',"ESRI Shapefile",shpDir,mapFile]

AND EVERYTHING WORKS!!

Thanks very much!

**Comment by vmora** [comment]
Ok, now that is progress. Normally the code should have told you that you have to set the path. If you can spare the time to open a ticket fro that, with the procedure to reproduce, I'll be thankful.

I see the changes, and I'm glad it works for your immediate use, but I'd rather have a more portable solution. Can you, do a 

```sh
which ogr2ogr
```

I a terminal an see what it tells you ?

**Comment by Bzzzzz** [comment]
It's : 
/usr/local/bin/ogr2ogr

I understand. I did not well configure the path of ogr2ogr. I re-do it and replace the wasp.py with the original version. This time it works.

I am very glad to 'open a ticket', but I do not understand what does it mean. Does it mean opening a new issue?

Thanks!!

**Comment by vmora** [comment]
Yes, ticket = issue, sorry for the wording.

I re-read the code and I see that the configuration dialog is popped-up when a function is called, so fixing the bug should simply be a matter of doing a second check:

Replace
```python
if not self.ogr2ogr : self.configure()
```
by
```python
if not self.ogr2ogr : self.configure()
if not self.ogr2ogr :
    QMessageBox.warning(self.iface.mainWindow(), "Warning", u'ogr2ogr path is not configured, aborting')
    return
```
Or better, you could change the configure() function to return true/false depending on the validity of the configuration and replace the calls by:
```python
if not configure(): return
```

And if you could test the configuration in the configure function (le.g. calling `ogr2ogr --version`) that would be even better.

So if you feel like contributing, a PR will be welcome.
