### ISSUE TITLE
The ogr2ogr configuration issue in ubuntu

### ISSUE THREAD

**Issue by Bzzzzz** [Oslandia/qgis-wasp#3]
This plug-in will sometimes forget to remind users to configure the path of ogr2ogr. 
If you import or export a wasp file before the configuration,  it will popup a error like this:
![screenshot from 2015-01-22 18 10 43](https://cloud.githubusercontent.com/assets/6636681/5853808/0fcbd032-a262-11e4-9643-ec5fa4b1fba7.png)

In ubuntu system, the ogr2ogr is located at /usr/local/bin/ogr2ogr after the installation of GDAL. It's better choosing to show all files but not only the executable. For some reason, the ogr2ogr won't appear in executable.

Thanks Vincent for his help.

**Comment by vpicavet** [comment]
Hi,

> In ubuntu system, the ogr2ogr is located at /usr/local/bin/ogr2ogr after the
> installation of GDAL. It's better choosing to show all files but not only
> the executable. For some reason, the ogr2ogr won't appear in executable.

ogr2ogr will not install in /usr/local if you install with packages.
It will probably be there if you recompile and make install gdal yourself.
If it is not executable, then you have a problem in your installation. And 
qgis-wasp will not be able to run it anyway.

Vincent
