### ISSUE TITLE
export problem for roughness file

### ISSUE THREAD

**Issue by Bzzzzz** [Oslandia/qgis-wasp#4]
Hi, 

This plug-in has a problem in exporting the roughness file. The roughness file exported is not correct for the roughness value.
I changed the line[143] :      
  if secondField.currentText() != '[second field]': fields += ','+firstField.currentText()
by
  if secondField.currentText() != '[second field]': fields += ','+secondField.currentText()
and problem solved.

Hope it will be helpful for the users of this plug-in.

**Comment by vmora** [comment]
Hi, thanks for the fix.
Could you make a pull request ?
